# Generated by Django 4.1 on 2022-09-04 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_car_photo_alter_car_car_photo_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 4, 13, 12, 48, 794009)),
        ),
    ]
